name: GitHub Actions Demo
on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name : ${{ github.ref }}"
      - uses: actions/checkout@v4
      - run: ls
      
  
